-- MySQL Script generated by MySQL Workbench
-- Sat Apr  7 13:41:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Developers` (
  `EmpID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `computerLanguage` VARCHAR(45) NULL,
  `Age` INT NULL,
  `StartDate` DATETIME NULL,
  `Salary` DECIMAL(8,2) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`EmpID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managers` (
  `MID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Age` VARCHAR(45) NULL,
  `Salary` VARCHAR(45) NULL,
  `StartDate` DATETIME NULL,
  PRIMARY KEY (`MID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QA` (
  `QID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Pay` DECIMAL(8,2) NULL,
  `StartDate` DATETIME NULL,
  PRIMARY KEY (`QID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `Project_PID` INT NOT NULL,
  `ProjectName` VARCHAR(45) NOT NULL,
  `ReleaseDate` DATETIME NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Version` VARCHAR(45) NULL,
  PRIMARY KEY (`Project_PID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ManagementAssignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ManagementAssignments` (
  `Managers_MID` INT NOT NULL,
  `Project_Project_PID` INT NOT NULL,
  PRIMARY KEY (`Managers_MID`, `Project_Project_PID`),
  INDEX `fk_ManagementAssignments_Project1_idx` (`Project_Project_PID` ASC),
  CONSTRAINT `fk_CurrentManagement_Managers1`
    FOREIGN KEY (`Managers_MID`)
    REFERENCES `mydb`.`Managers` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ManagementAssignments_Project1`
    FOREIGN KEY (`Project_Project_PID`)
    REFERENCES `mydb`.`Project` (`Project_PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QATeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QATeams` (
  `QA_QID` INT NOT NULL,
  `CurrentDevelopmentProject_Project_PID` INT NOT NULL,
  PRIMARY KEY (`QA_QID`, `CurrentDevelopmentProject_Project_PID`),
  INDEX `fk_QATeams_CurrentDevelopmentProject1_idx` (`CurrentDevelopmentProject_Project_PID` ASC),
  CONSTRAINT `fk_QATeams_QA1`
    FOREIGN KEY (`QA_QID`)
    REFERENCES `mydb`.`QA` (`QID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QATeams_CurrentDevelopmentProject1`
    FOREIGN KEY (`CurrentDevelopmentProject_Project_PID`)
    REFERENCES `mydb`.`Project` (`Project_PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeveloperAssignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeveloperAssignments` (
  `Developers_EmpID` INT NOT NULL,
  `CurrentDevelopmentProject_Project_PID` INT NOT NULL,
  PRIMARY KEY (`Developers_EmpID`, `CurrentDevelopmentProject_Project_PID`),
  INDEX `fk_DeveloperAssignments_CurrentDevelopmentProject1_idx` (`CurrentDevelopmentProject_Project_PID` ASC),
  CONSTRAINT `fk_DeveloperAssignments_Developers1`
    FOREIGN KEY (`Developers_EmpID`)
    REFERENCES `mydb`.`Developers` (`EmpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DeveloperAssignments_CurrentDevelopmentProject1`
    FOREIGN KEY (`CurrentDevelopmentProject_Project_PID`)
    REFERENCES `mydb`.`Project` (`Project_PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PR` (
  `PID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Age` VARCHAR(45) NULL,
  `Salary` DECIMAL(8,2) NULL,
  `StartDate` DATETIME NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRTeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRTeams` (
  `PR_PID` INT NOT NULL,
  `Project_Project_PID` INT NOT NULL,
  PRIMARY KEY (`PR_PID`, `Project_Project_PID`),
  INDEX `fk_PRTeams_Project1_idx` (`Project_Project_PID` ASC),
  CONSTRAINT `fk_PRTeams_PR1`
    FOREIGN KEY (`PR_PID`)
    REFERENCES `mydb`.`PR` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRTeams_Project1`
    FOREIGN KEY (`Project_Project_PID`)
    REFERENCES `mydb`.`Project` (`Project_PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `age` INT NULL,
  `newsletter` TINYINT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITStaff` (
  `ITID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Age` VARCHAR(45) NULL,
  `Pay` VARCHAR(45) NULL,
  `StartDate` DATETIME NULL,
  PRIMARY KEY (`ITID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLANNEDPATCHES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLANNEDPATCHES` (
  `PATCHID` INT NOT NULL,
  PRIMARY KEY (`PATCHID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `TID` INT NOT NULL,
  `Description` VARCHAR(90) NOT NULL,
  `Resolved` TINYINT NOT NULL,
  `Users_UID` INT NULL,
  `ITStaff_ITID` INT NOT NULL,
  `Managers_MID` INT NULL,
  `PLANNEDPATCHES_PATCHID` INT NULL,
  `Developers_EmpID` INT NULL,
  `QA_QID` INT NULL,
  PRIMARY KEY (`TID`, `Users_UID`),
  INDEX `fk_Tickets_Users1_idx` (`Users_UID` ASC),
  INDEX `fk_Tickets_ITStaff1_idx` (`ITStaff_ITID` ASC),
  INDEX `fk_Tickets_Managers1_idx` (`Managers_MID` ASC),
  INDEX `fk_Tickets_PLANNEDPATCHES1_idx` (`PLANNEDPATCHES_PATCHID` ASC),
  INDEX `fk_Tickets_Developers1_idx` (`Developers_EmpID` ASC),
  INDEX `fk_Tickets_QA1_idx` (`QA_QID` ASC),
  CONSTRAINT `fk_Tickets_Users1`
    FOREIGN KEY (`Users_UID`)
    REFERENCES `mydb`.`Users` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_ITStaff1`
    FOREIGN KEY (`ITStaff_ITID`)
    REFERENCES `mydb`.`ITStaff` (`ITID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Managers1`
    FOREIGN KEY (`Managers_MID`)
    REFERENCES `mydb`.`Managers` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_PLANNEDPATCHES1`
    FOREIGN KEY (`PLANNEDPATCHES_PATCHID`)
    REFERENCES `mydb`.`PLANNEDPATCHES` (`PATCHID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Developers1`
    FOREIGN KEY (`Developers_EmpID`)
    REFERENCES `mydb`.`Developers` (`EmpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_QA1`
    FOREIGN KEY (`QA_QID`)
    REFERENCES `mydb`.`QA` (`QID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devPatchTeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devPatchTeams` (
  `Developers_EmpID` INT NOT NULL,
  `PLANNEDPATCHES_PATCHID` INT NOT NULL,
  PRIMARY KEY (`Developers_EmpID`, `PLANNEDPATCHES_PATCHID`),
  INDEX `fk_devPatchTeams_PLANNEDPATCHES1_idx` (`PLANNEDPATCHES_PATCHID` ASC),
  CONSTRAINT `fk_devPatchTeams_Developers1`
    FOREIGN KEY (`Developers_EmpID`)
    REFERENCES `mydb`.`Developers` (`EmpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devPatchTeams_PLANNEDPATCHES1`
    FOREIGN KEY (`PLANNEDPATCHES_PATCHID`)
    REFERENCES `mydb`.`PLANNEDPATCHES` (`PATCHID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QAPatchTeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QAPatchTeams` (
  `QA_QID` INT NOT NULL,
  `PLANNEDPATCHES_PATCHID` INT NOT NULL,
  PRIMARY KEY (`QA_QID`, `PLANNEDPATCHES_PATCHID`),
  INDEX `fk_QAPatchTeams_PLANNEDPATCHES1_idx` (`PLANNEDPATCHES_PATCHID` ASC),
  CONSTRAINT `fk_QAPatchTeams_QA1`
    FOREIGN KEY (`QA_QID`)
    REFERENCES `mydb`.`QA` (`QID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QAPatchTeams_PLANNEDPATCHES1`
    FOREIGN KEY (`PLANNEDPATCHES_PATCHID`)
    REFERENCES `mydb`.`PLANNEDPATCHES` (`PATCHID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `PID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `ReleaseDate` DATETIME NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PurchaseHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseHistory` (
  `TID` INT NOT NULL,
  `TimeOfPurchase` DATETIME NULL,
  `Price` DECIMAL(5,2) NULL,
  `Users_UID` INT NOT NULL,
  `Projects_PID` INT NOT NULL,
  PRIMARY KEY (`TID`, `Users_UID`, `Projects_PID`),
  INDEX `fk_PurchaseHistory_Users1_idx` (`Users_UID` ASC),
  INDEX `fk_PurchaseHistory_Projects1_idx` (`Projects_PID` ASC),
  CONSTRAINT `fk_PurchaseHistory_Users1`
    FOREIGN KEY (`Users_UID`)
    REFERENCES `mydb`.`Users` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PurchaseHistory_Projects1`
    FOREIGN KEY (`Projects_PID`)
    REFERENCES `mydb`.`Projects` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
